### ISSUE TITLE
Shadow Priest: Off GCD Not working

### ISSUE THREAD

**Issue by RussellAnas** [herotc/hero-rotation#683]
Hi,
'Surrender to madness' keeps showing as a main spell even when 'show as off gcd' is selected. Please fix!

**Comment by Cilraaz** [comment]
This has been "fixed" in commit https://github.com/herotc/hero-rotation/commit/87cc6e7eacd0c1cb61b82db56e9bf81e4e612bcc

The option for OffGCD has been removed, as the spell is only called via CastCycle, which can only display on main icon or left nameplate.

**Comment by Cilraaz** [comment]
This has been changed. OffGCD should now work for Surrender to Madness.

**Comment by RussellAnas** [comment]
I just installed the alpha version but it's still not working. Surrender to Madness is shown on main icon instead of off gcd slot even when off gcd slot is enabled.

**Comment by Cilraaz** [comment]
CurseForge hasn't packaged alpha versions for us in months. It'll be included in the 9.0.2.19 release, or you can download it from github.

**Comment by RussellAnas** [comment]
Thanks for the quick turn around!!!
