### ISSUE TITLE
[Subtlety, Rogue]: SoD recommendations with t30 set bonus

### ISSUE THREAD

**Issue by ipryan87** [herotc/hero-rotation#954]
### What version of HeroRotation are you using?

10.1.0.09

### What version of HeroLib are you using?

10.1.0.03

### What version of HeroDBC are you using?

10.1.0.01

### What is the issue?

When playing with the 2 piece subtlety tier bonus, recommendation for symbols and shadow dance seem to be incorrect. SoD is being recommended while already having the 2p SoD buff from shadow dance in the opener. Simc recommends using shadow dance first, then using symbols of death four seconds into dance to provide full use of pandemic window. Rupture also isnt being recommended after first use of flag in the opener. 

Simc opener:
SS->SB/pot->gb->Flag->Rupture->Sd->gb->evis->SS->St/cb->SoD->Vanish->SS

Beacon of Beyond also seems to be recommended during stealth, which seems to go against SimC as well, preferring to use it before SB on opener, or very late into opener after last Vanish/SS combo while still benefiting from SoD.

### Icon Behavior

None

**Comment by Furizaa** [comment]
Should be fixed now with https://github.com/herotc/hero-rotation/pull/946

**Comment by NStrategy** [comment]
While Beacon is now functioning, the issue with rotation still persists. The SoD interaction only really works just after you've used SD - when SD has 5 more seconds of cooldown, but SoD is available, it will recommend SoD, which should not be the case. Also, the talent - The First Dance - is not considered at all, suggesting to use SD+GB at 4 combo points although you receive 4 combo points from activating SD.

**Comment by framara** [comment]
on current build/main branch, it recommends to evis when there are 3+ targets. Priority rotation is set to never. 

![image](https://github.com/herotc/hero-rotation/assets/452670/12ceb28b-95c1-4a51-95cb-e3a2c13ee91b)

**Comment by Cilraaz** [comment]
The issue with Black Powder not being recommended was fixed in commit https://github.com/herotc/hero-rotation/commit/deae9393548c67291392bdc3ad4677d1e69b04ec

It's also not relevant to this issue.

**Comment by Furizaa** [comment]
I already found another issue with ShD in the code for which I have a fix locally (`S.ShadowDance` vs `S.ShadowDanceTalent`). Currently investigating the Rupture thing. Not sure if it will fix all the reported issues tho.

**Comment by NStrategy** [comment]
> 

If you mean by "the Rupture thing" the fact that it does not get shown in the opener, that is because of Shadow Dance having too much prio, or so I would say it in laymen terms. If you set Shadow Dance to " show as Off GCD", it shows the opener correctly. However, Shadow Dance still gets recommended as a top icon as soon as you SS out of stealth, so somehow, the APL wants to force you to use Shadow Dance or something along those lines.

**Comment by Furizaa** [comment]
Yeah, this issue is a bit beyond my capabilities TBH. I have a hacky way of solving this now but it's not something I would make a commit for:

```lua
local function StealthMacro (StealthSpell, EnergyThreshold)
-- ...
  if MacroAbility == S.Rupture then
    if HR.Cast(S.Rupture) then return "Cast Rupture (Pre Stealth)" end
    return false
  end
``` 

<img width="363" alt="image" src="https://github.com/herotc/hero-rotation/assets/365742/2e110356-94f6-4677-acc0-13d892a87f14">

Anyway, I make fix for the `S.ShadowDanceTalent` thing that I broke later and leave the Rupture to the pros.

**Comment by NStrategy** [comment]
Sounds great, hope Koji or Fuu can fix the issue

**Comment by EvanMichaels** [comment]
I believe all of these issues (at least with regard to the current committed APL, not Fuu's experimental one) are resolved at this point.
